### ISSUE TITLE
Plugin is officially broken 2022

### ISSUE THREAD

**Issue by Desenrrollado** [ADoesGit/ringtoner#10]
Alot of classes have been changed within discord. This has resulted in only the sounds for the default sounds in Powercord increasing. Other then that this plugin no longer works. It would be nice to at least have it work again. Sure adding support for local file sounds would be on of the nice things to add on top of this. Though it's not required. Thanks in any case if you fix this....

**Comment by AAGaming00** [comment]
Sorry but I don't use Powercord anymore and therefore cannot fix it.If someone wants to take over maintaining this (and some of my other plugins) let me know.On Jan 22, 2022 8:53 PM, Desenrrollado ***@***.***> wrote:
Alot of classes have been changed within discord. This has resulted in only the sounds for the default sounds in Powercord increasing. Other then that this plugin no longer works. It would be nice to at least have it work again. Sure adding support for local file sounds would be on of the nice things to add on top of this. Though it's not required. Thanks in any case if you fix this....

**Comment by BluSpring** [comment]
I can try to see what I can do in getting this to work later when I have the time
